<a href="https://colab.research.google.com/github/Felipepa9/MADSI/blob/main/ENTREGA_2_%7C%7C_CIENCIA_DE_DATOS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('/content/drive/MyDrive/CIENCIA DE DATOS/datos.csv')

data.head()

,scheduled_flight_leg_block_off_date,scheduled_flight_leg_block_off_time,scheduled_flight_leg_block_off_date_utc,scheduled_flight_leg_block_off_time_utc,marketing_airline_code,operating_flight_num,origin_leg_iata_airport_code,destination_leg_iata_airport_code,flight_leg_registration_code,actual_flight_leg_fleet_name,...,FLIGHT_KEY,POS_DISP_TOTALES,total_pax_qty,total_capacity_leg_qty,fo_pct,pax_weight_kg_qty,pax_bags_qty,pax_bags_net_weight_kg_qty,total_pax_qty_est,maximum_payload_kg_qty
0,2024-11-09,23:35:00,2024-11-09,22:35:00,LA,705,MAD,SCL,CCBGA,B789,...,705MADSCL2024-11-09,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-09,22:40:00,2024-11-09,21:40:00,LA,8065,MAD,GRU,CCBGI,B789,...,8065MADGRU2024-11-09,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-11-09,15:30:00,2024-11-09,14:30:00,LA,711,MAD,BOG,CCBBB,B787,...,711MADBOG2024-11-09,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-11-09,00:45:00,2024-11-08,23:45:00,LA,2485,MAD,LIM,CCBGD,B789,...,2485MADLIM2024-11-09,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-11-08,00:45:00,2024-11-07,23:45:00,LA,2485,MAD,LIM,CCBGN,B789,...,2485MADLIM2024-11-08,36,290.0,300.0,0.966667,NaN,NaN,NaN,NaN,NaN

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 533 entries, 0 to 532
Data columns (total 21 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   scheduled_flight_leg_block_off_date      533 non-null    object
 1   scheduled_flight_leg_block_off_time      533 non-null    object
 2   scheduled_flight_leg_block_off_date_utc  533 non-null    object
 3   scheduled_flight_leg_block_off_time_utc  533 non-null    object
 4   marketing_airline_code                   533 non-null    object
 5   operating_flight_num                     533 non-null    int64
 6   origin_leg_iata_airport_code             533 non-null    object
 7   destination_leg_iata_airport_code        533 non-null    object
 8   flight_leg_registration_code             529 non-null    object
 9   actual_flight_leg_fleet_name             529 non-null    object
 10  actual_flight_leg_fleet_name_code        529 non-null    object
 11  FLIGHT_KEY                               533 non-null    object
 12  POS_DISP_TOTALES                         533 non-null    int64
 13  total_pax_qty                            501 non-null    float64
 14  total_capacity_leg_qty                   501 non-null    float64
 15  fo_pct                                   501 non-null    float64
 16  pax_weight_kg_qty                        457 non-null    float64
 17  pax_bags_qty                             458 non-null    float64
 18  pax_bags_net_weight_kg_qty               458 non-null    float64
 19  total_pax_qty_est                        457 non-null    float64
 20  maximum_payload_kg_qty                   458 non-null    float64
dtypes: float64(8), int64(2), object(11)
memory usage: 87.6+ KB

In [6]:
data.describe()

,operating_flight_num,POS_DISP_TOTALES,total_pax_qty,total_capacity_leg_qty,fo_pct,pax_weight_kg_qty,pax_bags_qty,pax_bags_net_weight_kg_qty,total_pax_qty_est,maximum_payload_kg_qty
count,533.000000,533.000000,501.000000,501.000000,501.000000,457.000000,458.000000,458.000000,457.000000,458.000000
mean,3266.287054,34.874296,264.904192,300.958084,0.880348,22060.739606,271.231441,4835.687773,268.402626,46684.919214
std,3252.059551,5.672215,56.676157,49.748329,0.119623,5152.885659,93.833591,1574.412914,62.679180,9952.779557
min,705.000000,0.000000,100.000000,243.000000,0.326829,0.000000,0.000000,0.000000,0.000000,20324.000000
25%,707.000000,36.000000,231.000000,298.000000,0.836585,19214.000000,203.250000,3675.750000,234.000000,41071.250000
50%,1107.000000,36.000000,272.000000,300.000000,0.923333,22818.000000,273.000000,4975.000000,278.000000,44443.500000
75%,8065.000000,36.000000,289.000000,300.000000,0.956667,24240.000000,313.750000,5691.000000,295.000000,54044.000000
max,9957.000000,44.000000,408.000000,410.000000,1.082305,34181.000000,843.000000,16113.000000,409.000000,67180.000000

In [7]:
data.isnull().sum()

scheduled_flight_leg_block_off_date         0
scheduled_flight_leg_block_off_time         0
scheduled_flight_leg_block_off_date_utc     0
scheduled_flight_leg_block_off_time_utc     0
marketing_airline_code                      0
operating_flight_num                        0
origin_leg_iata_airport_code                0
destination_leg_iata_airport_code           0
flight_leg_registration_code                4
actual_flight_leg_fleet_name                4
actual_flight_leg_fleet_name_code           4
FLIGHT_KEY                                  0
POS_DISP_TOTALES                            0
total_pax_qty                              32
total_capacity_leg_qty                     32
fo_pct                                     32
pax_weight_kg_qty                          76
pax_bags_qty                               75
pax_bags_net_weight_kg_qty                 75
total_pax_qty_est                          76
maximum_payload_kg_qty                     75
dtype: int64

In [9]:
data['total_pax_qty'] = data['total_pax_qty'].fillna(round(data['total_pax_qty'].mean(),1))
data['total_capacity_leg_qty'] = data['total_capacity_leg_qty'].fillna(round(data['total_capacity_leg_qty'].mean(),1))
data['fo_pct'] = data['fo_pct'].fillna(round(data['fo_pct'].mean(),1))

In [10]:
data.isnull().sum()

scheduled_flight_leg_block_off_date         0
scheduled_flight_leg_block_off_time         0
scheduled_flight_leg_block_off_date_utc     0
scheduled_flight_leg_block_off_time_utc     0
marketing_airline_code                      0
operating_flight_num                        0
origin_leg_iata_airport_code                0
destination_leg_iata_airport_code           0
flight_leg_registration_code                4
actual_flight_leg_fleet_name                4
actual_flight_leg_fleet_name_code           4
FLIGHT_KEY                                  0
POS_DISP_TOTALES                            0
total_pax_qty                               0
total_capacity_leg_qty                      0
fo_pct                                      0
pax_weight_kg_qty                          76
pax_bags_qty                               75
pax_bags_net_weight_kg_qty                 75
total_pax_qty_est                          76
maximum_payload_kg_qty                     75
dtype: int64

In [22]:
data.dropna(subset=['flight_leg_registration_code','actual_flight_leg_fleet_name','actual_flight_leg_fleet_name_code'], inplace=True)

In [24]:
data.isnull().sum()

scheduled_flight_leg_block_off_date         0
scheduled_flight_leg_block_off_time         0
scheduled_flight_leg_block_off_date_utc     0
scheduled_flight_leg_block_off_time_utc     0
marketing_airline_code                      0
operating_flight_num                        0
origin_leg_iata_airport_code                0
destination_leg_iata_airport_code           0
flight_leg_registration_code                0
actual_flight_leg_fleet_name                0
actual_flight_leg_fleet_name_code           0
FLIGHT_KEY                                  0
POS_DISP_TOTALES                            0
total_pax_qty                               0
total_capacity_leg_qty                      0
fo_pct                                      0
pax_weight_kg_qty                          72
pax_bags_qty                               71
pax_bags_net_weight_kg_qty                 71
total_pax_qty_est                          72
maximum_payload_kg_qty                     71
dtype: int64